### ISSUE TITLE
Instructions not clear: too much complicated

### ISSUE THREAD

**Issue by blauer4** [HS-Tools/HS-BG-Leaderboards-Bot#105]
Hello, 
I was trying to use the bot to help a streamer set it up on his channel, but the process is really painful, and the streamer I'm helping has really limited technical capacity. I cannot understand what I need to do in order to add the bot to the channel, do I need to add it to the default list? Doesn't it have to be added through an Oauth token of twitch? Do I need to run it locally?

I understood that it uses docker, but it isn't clear actually how the bot interacts with twitch. Plus I tried to run the docker and it gives me the following result: 
```py
Traceback (most recent call last):
  File "twitch.py", line 10, in <module>
    leaderboardBot = LeaderBoardBot()
  File "/src/leaderboardBot.py", line 29, in __init__
    table_name = os.environ['TABLE_NAME']
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'TABLE_NAME'
```
Do I need to download anyway the files of the testing section? Anything helpful is appreciated. 
The problem in my opinion is that the documentation is not so clear, so it would be really helpful to understand how the bot works and if I only have to request to add the channel to the `default_list`. FYI the channel I'm trying to add this bot is [Budilicious](https://www.twitch.tv/budilicious)
I could even help you write a clearer documentation, once I understand what I should be supposed to do to make it run.

Cheers,
Lollixz

**Comment by quinnabrvau** [comment]
Hi,
No need to run the bot yourself. If you go to lii's discord, you can add the bot. Go to wall-lii-requests and then checked the pinned message for how to use `!add_channel` 
discord: [https://discord.com/invite/C6NguFf](https://discord.com/invite/C6NguFf)

We should probably add some documentation to the main page for how to add yourself to the bot.

**Comment by blauer4** [comment]
Thanks, maybe I will do a pr if I have time to add those information! Thank you for the response, closed as resolved
